<?php 
header("Content-type: text/css");
require_once("../classes/class.css.php");
require_once("../classes/class.loader.php");
require_once("../classes/class.misc.php");
?>
/* Generated by Font Squirrel (http://www.fontsquirrel.com) */

<?PHP 
echo loader::auto_load_webfonts('../fonts/Ubuntu/');

// AUTO-LOAD FONTS
echo loader::auto_load_webfonts();
?>